In [21]:


class Item() :
    def __init__(self , weight , profit , name = "" ) :
        self.weight = weight
        self.profit = profit
        self.name = name
        self.pbw = self.profit / self.weight

    def __lt__(self, item ) :
        return self.profit < item.profit


In [22]:

store = [
    Item(2 , 1),
    Item(3 , 2),
    Item(4 , 5),
    Item(5 , 6)
]

M = 8

In [23]:
import numpy as np

In [24]:
V = np.zeros((len(store) + 1 , M + 1) , np.int8)
V

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [26]:
for i in range(len(V) + 1) : 
    for w in range(M+1) :

        if i == 0 or w == 0 :
            V[i][w] = 0 
        
        elif ( store[i-1].weight <= w) :
            V[i][w] = max(V[i-1][w] , V[i-1][w - store[i-1].weight] + store[i-1].profit)
        else :
            V[i-1][w] = 0 

        


IndexError: index 5 is out of bounds for axis 0 with size 5

In [20]:
V

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 2, 2, 3, 3, 3, 3],
       [0, 0, 0, 0, 5, 5, 5, 7, 7],
       [0, 0, 0, 0, 0, 6, 6, 7, 7]], dtype=int8)

In [40]:




val = [1,2,5,6]
wt = [2,3,4,5]
W = 8

n = len(store)




# K = [[0 for x in range(W + 1)] for x in range(n + 1)]
K = np.zeros((n+1 , W+1) , np.int8)


for i in range(n + 1):
	for w in range(W + 1):
		if i == 0 or w == 0:
			K[i][w] = 0
		elif wt[i-1] <= w:
			K[i][w] = max(store[i-1].profit
					+ K[i-1][w - store[i-1].weight],
						K[i-1][w])
		else:
			K[i][w] = K[i-1][w]

print(K[n][W])



8


In [41]:
for row in K :
    print(row)

[0 0 0 0 0 0 0 0 0]
[0 0 1 1 1 1 1 1 1]
[0 0 1 2 2 3 3 3 3]
[0 0 1 2 5 5 6 7 7]
[0 0 1 2 5 6 6 7 8]
