In [11]:

def define_matrix() : 

    rows, cols = list(map(int , input("Enter Number of Rows and Columns -> ").rstrip().split()))
    print(f"ROWS - {rows} COLUMNS - {cols}")

    arr = []
    for i in range(rows) :
        temp = list(map(int , input(f"{i}th row - ").rstrip().split()))
        if len(temp) != cols :
            print("Index Out of Bounds ! Column size didnt match")
            return 
        else :
            arr.append(temp)

    # print(arr)
    return arr

print("MATRIX 1 : ")
mat1 = define_matrix()

print("MATRIX 2 : ")
mat2 = define_matrix()

if len(mat1[0]) != len(mat2) :
    print("Cant perform matrix multiplication as the number of columns in the first matrix must be equal to the number of rows in the second matrix.")

MATRIX 1 : 


ValueError: not enough values to unpack (expected 2, got 0)

In [12]:
mat1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

mat2 = [
    [2,3,4],
    [6,7,8],
    [7,1,3]
]

In [10]:
import numpy as np
import time

In [3]:
def calculateCell(matA , matB, pos , mulmat) :
    ans = 0 
    for k in range(len(matB)) :
        ans += matA[pos[0]][k] * matB[k][pos[1]]
    mulmat[pos[0]][pos[1]] = ans
    time.sleep(1) # To make the computation time costly


### Numpy Method - dot()

In [4]:

def numpy_method(matA , matB) : 

    return np.dot(matA , matB)

start = time.perf_counter()

mulmat = numpy_method(mat1 , mat2)
print(mulmat)

end = time.perf_counter()

print(f"Finished in {round(end - start , 4)} second(s).")


[[ 35  20  29]
 [ 80  53  74]
 [125  86 119]]
Finished in 0.0005 second(s).


### Nested Loops Method 

In [13]:
def matrix_multiplication(mat1 , mat2) :

    mulmat = np.zeros((len(mat1) , len(mat2[0])) , np.int8)
    
    for i in range(len(mat1)) :
        for j in range(len(mat2[0])) :
            calculateCell(mat1 , mat2 , [i,j] , mulmat)

    return mulmat




In [14]:
start = time.perf_counter()
mulmat = matrix_multiplication(mat1 , mat2)
print(mulmat)

end = time.perf_counter()

print(f"Finished in {round(end - start , 4)} second(s).")

[[ 35  20  29]
 [ 80  53  74]
 [125  86 119]]
Finished in 9.0295 second(s).


### Multithreading Matrix Multiplication

In [7]:
import threading
import concurrent.futures 
import numpy as np
import time

Using threading.thread() from threading module 

In [16]:
def multithreading_matrix_multiplication1(mat1 , mat2) :
    threads = []

    mulmat = np.zeros((len(mat1[0]) , len(mat2)) , dtype = np.int8)
    for i in range(len(mat1[0])) :
        for j in range(len(mat2)) :
            th = threading.Thread(target = calculateCell , args= [mat1 , mat2 , [i , j] , mulmat])
            th.start()
            threads.append(th)

    for th in threads :
        th.join()
    # it will wait till all the threads are executed
    
    return mulmat

In [17]:
start = time.perf_counter()
print(multithreading_matrix_multiplication1(mat1 , mat2))
end = time.perf_counter()

print(f"Finished in {round(end - start , 4)} second(s).")

[[ 35  20  29]
 [ 80  53  74]
 [125  86 119]]
Finished in 1.0072 second(s).


Using ThreadPoolExecuter() from concurrent.futures module

In [ ]:

def multithreading_matrix_multiplication2(mat1 , mat2) :

    threads = []
    mulmat = np.zeros((len(mat1[0]) , len(mat2)),dtype = np.int8)
    
    with concurrent.futures.ThreadPoolExecutor() as executer : 
        for i in range(len(mat1[0])) :
            for j in range(len(mat2)) :
                threads.append(executer.submit(calculateCell , mat1 , mat2 , [i,j] , mulmat))

    return mulmat
                


In [ ]:
start = time.perf_counter()
print(multithreading_matrix_multiplication2(mat1 , mat2))
end = time.perf_counter()

print(f"Finished in {round(end - start , 4)} second(s).")


[[ 35  20  29]
 [ 80  53  74]
 [125  86 119]]
Finished in 1.0061 second(s).
